#!/bin/sh

#run check_run_codeML
# [parameters] input_fasta working_dir skip_code_ml 

input_fasta=$1
working_dir=$2

if [ "$#" -eq 2 ]; then
    if grep -xq ${input_fasta} ${working_dir}/to_be_reevaluated_by_codeML
    then
        exit 0
    else
        exit 1
    fi
else
    exit 1
fi
