#!/bin/sh

#Check for positively selected amino acids
#To be used with run_FUBAR only
# [parameters] file FUBAR_results_dir workingpath

TEMP=$(mktemp -d /tmp/pos_FUBAR_temp_$1_.XXXXXXXX)

touch $3/FUBAR_short_list $3/to_be_reevaluated_by_codeML
cat $3/$2/$1 | grep 'Pos. posterior' > $TEMP/$1.pos
if [ -s $TEMP/$1.pos ]
	then 
	echo $1 >> $3/FUBAR_short_list && sed -i "s%.fubar%%g" $3/FUBAR_short_list
else
	echo $1 >> $3/to_be_reevaluated_by_codeML && sed -i "s%.fubar%%g" $3/to_be_reevaluated_by_codeML
fi

rm -r $TEMP
