#!/bin/sh

#Checking for positively selected amino acid sites
# [parameters] file codeML_results_dir workingpath

TEMP=$(mktemp -d  /tmp/pos_codeML_temp_$1_.XXXXXXXX)

grep "p:" $3/$2/$1.codeml.out > $TEMP/temp1.$1
grep "w:" $3/$2/$1.codeml.out > $TEMP/temp4.$1
tail -1 $TEMP/temp1.$1 > $TEMP/temp2.$1
cut -f 8 -d ' ' $TEMP/temp2.$1 > $TEMP/temp3.$1
cut -f 8 -d ' ' $TEMP/temp4.$1 > $TEMP/temp5.$1
checkp=$(cat $TEMP/temp3.$1)
checkw=$(cat $TEMP/temp5.$1)
checkp1="0.00000"
checkw1="1.00000"
echo $check $check1
if [ "$checkp" = "$checkp1" ] || [ "$checkw" = "$checkw1" ]
	then 
	echo $1 >> $3/negative_list
else
	echo $1 >> $3/codeML_short_list
fi

rm -r $TEMP
