#!/bin/sh

#run FUBAR
# [parameters] file FUBAR_files_dir FUBAR_config_files_dir FUBAR_results_dir workingpath

# HYPHY settings

echo "1" > $5/$2/$3/$1
echo "4" >> $5/$2/$3/$1
echo "1" >> $5/$2/$3/$1
echo $5/$2/$1 >> $5/$2/$3/$1
echo "Y" >> $5/$2/$3/$1
echo "20" >> $5/$2/$3/$1
echo "3" >> $5/$2/$3/$1
echo "0.5" >> $5/$2/$3/$1

# Run FUBAR

cat $5/$2/$3/$1 | HYPHYMP > $5/$4/$1
touch $5/$2/$1.fubar.cache $5/$2/$1.FUBAR.json && rm $5/$2/$1.fubar.cache $5/$2/$1.FUBAR.json
